"""Immutable authored Newton domain. Numerical results belong to a later solver."""

from .coordinates import (
    AccelerationVector,
    CartesianCoordinates,
    CartesianDirection,
    Coordinates,
    ForceVector,
    SurfaceCoordinates,
    SurfaceDirection,
)
from .interactions import (
    AuthoredAcceleration,
    BodyReference,
    Contact,
    EnvironmentReference,
    ForceSource,
    Friction,
    FrictionRegime,
    GravitationalField,
    GravitationalInteraction,
    NewtonAssumptions,
    NewtonBody,
    StringConnection,
    Surface,
    SystemBoundary,
    ThirdLawPair,
)
from .scenario import Force, ForceKind, NewtonScenario
from .values import (
    FrictionCoefficient,
    Kilograms,
    Metres,
    MetresPerSecondSquared,
    Newtons,
    UnknownValue,
)

__all__ = [
    "AccelerationVector",
    "AuthoredAcceleration",
    "BodyReference",
    "CartesianCoordinates",
    "CartesianDirection",
    "Contact",
    "Coordinates",
    "EnvironmentReference",
    "Force",
    "ForceKind",
    "ForceSource",
    "ForceVector",
    "Friction",
    "FrictionCoefficient",
    "FrictionRegime",
    "GravitationalField",
    "GravitationalInteraction",
    "Kilograms",
    "Metres",
    "MetresPerSecondSquared",
    "NewtonAssumptions",
    "NewtonBody",
    "Newtons",
    "NewtonScenario",
    "StringConnection",
    "Surface",
    "SurfaceCoordinates",
    "SurfaceDirection",
    "SystemBoundary",
    "ThirdLawPair",
    "UnknownValue",
]
