"""Mechanics domain models and deterministic scenario factories."""

from .momentum_conceptual_questions import (
    ConceptualQuestionOptions,
    ConceptualTemplate,
    MomentumConceptualQuestionGenerator,
)
from .momentum_constrained_solver import (
    CollisionClassification,
    ConstrainedCollisionSolution,
    ConstrainedMomentumSolver,
    DerivedFinalBodyState,
)
from .momentum_generation import (
    DEFAULT_MOMENTUM_PROBLEM_GENERATION_POLICY,
    GeneratedCollisionProblem,
    GeneratedContactTimeProblem,
    GeneratedForceFromMomentumChangeProblem,
    GeneratedImpulseForceTimeProblem,
    GeneratedInitialMomentumProblem,
    GeneratedMomentumChangeProblem,
    MomentumGeneratedProblem,
    MomentumGenerationFamily,
    MomentumProblemDifficultyProfile,
    MomentumProblemFactory,
    MomentumProblemGenerationInput,
    MomentumProblemGenerationPolicy,
)
from .momentum_impulse import (
    Impulse,
    Kilograms,
    KineticEnergy,
    MetresPerSecond,
    Momentum,
    MomentumBody,
    MomentumChange,
    MomentumScenario,
    Newtons,
    PhysicalDirection,
    PositiveAxis,
    Seconds,
    SystemBoundary,
)
from .momentum_impulse_relationships import (
    ContactTimeResult,
    ForceTimeInput,
    ForceTimeResult,
    ImpulseResult,
    MomentumChangeInput,
    MomentumChangeResult,
    MomentumImpulseRelationshipSolver,
)
from .momentum_impulse_scenario_factory import (
    DEFAULT_MOMENTUM_GENERATION_POLICY,
    MomentumDifficultyProfile,
    MomentumGenerationPolicy,
    MomentumScenarioFactory,
    MomentumScenarioFamily,
    MomentumScenarioGenerationInput,
)
from .momentum_impulse_solver import (
    BodyMomentumResult,
    MomentumImpulseSolution,
    MomentumImpulseSolver,
)
from .momentum_interaction import (
    CommonFinalVelocityConstraint,
    CompleteFinalStateConstraint,
    FinalBodyState,
    InteractionConstraint,
    InteractionConstraintKind,
    KnownFinalVelocityConstraint,
    MomentumInteraction,
)
from .momentum_question_generator import (
    MomentumQuestionGenerator,
    MomentumQuestionOptions,
    MomentumQuestionTemplate,
)
from .newton_conceptual_questions import (
    GENERATOR_ID as NEWTON_CONCEPTUAL_GENERATOR_ID,
)
from .newton_conceptual_questions import (
    GENERATOR_VERSION as NEWTON_CONCEPTUAL_GENERATOR_VERSION,
)
from .newton_conceptual_questions import (
    NewtonConceptualQuestionGenerator,
    NewtonConceptualQuestionOptions,
    NewtonConceptualTemplate,
    NewtonQuestionTemplate,
)
from .newton_conceptual_questions import (
    NewtonQuestionOptions as NewtonConceptualOptions,
)
from .newton_generation import (
    DEFAULT_NEWTON_GENERATION_POLICY,
    DEFAULT_NEWTON_PROBLEM_FACTORY,
    GENERATOR_ID,
    GENERATOR_VERSION,
    POLICY_VERSION,
    GeneratedConnectedBodiesProblem,
    GeneratedContactProblem,
    GeneratedEquilibriumProblem,
    GeneratedGravitationProblem,
    GeneratedNewtonIIProblem,
    GeneratedNewtonProblem,
    GeneratedThirdLawProblem,
    GeneratedUnknownForceProblem,
    GeneratedWeightProblem,
    NewtonDifficultyProfile,
    NewtonGeneratedMetadata,
    NewtonGeneratedProblem,
    NewtonGenerationFamily,
    NewtonGenerationInput,
    NewtonGenerationPolicy,
    NewtonProblemFactory,
)
from .newton_question_generator import (
    GENERATOR_ID as NEWTON_QUESTION_GENERATOR_ID,
)
from .newton_question_generator import (
    GENERATOR_VERSION as NEWTON_QUESTION_GENERATOR_VERSION,
)
from .newton_question_generator import (
    NewtonCalculationQuestionGenerator,
    NewtonCalculationTemplate,
    NewtonQuestionGenerator,
    NewtonQuestionOptions,
)
from .newton_solver import (
    GRAVITATIONAL_CONSTANT,
    SOLVER_ID,
    SOLVER_VERSION,
    VALIDATION_TOLERANCE,
    BodyDynamicsResult,
    ComponentSign,
    ConnectedBodiesResult,
    ContactResult,
    FailureReason,
    ForceResult,
    FrictionResult,
    GravitationalResult,
    NewtonSolveError,
    NewtonSolver,
    ResultantResult,
    StraightStringRequest,
    WeightResult,
)
from .vertical_projectile_scenario_factory import (
    DEFAULT_GENERATION_POLICY,
    DifficultyProfile,
    ScenarioFamily,
    ScenarioGenerationInput,
    VerticalProjectileGenerationPolicy,
    VerticalProjectileScenarioFactory,
)
from .work_energy_power import (
    AlongPlaneWorkInput,
    AngleDegrees,
    AveragePowerInput,
    ConstantSpeedPowerInput,
    ContactCondition,
    Displacement,
    EnergyState,
    ForceAlongMotion,
    ForceEnergyClassification,
    ForceMagnitude,
    GravitationalFieldMagnitude,
    HeightState,
    KineticState,
    Mass,
    MassFlowRate,
    MechanicalEnergyContext,
    NetWorkInput,
    PumpingPowerInput,
    ReferenceLevel,
    RelativeHeight,
    SignedEnergy,
    SignedForce,
    Speed,
    SurfaceContext,
    TimeInterval,
    WorkContribution,
    WorkEnergyAssumptions,
    WorkEnergyContext,
    WorkEnergyScenario,
)
from .work_energy_power import (
    UnknownValue as WorkEnergyUnknownValue,
)
from .work_energy_power_generation import (
    DEFAULT_WORK_ENERGY_GENERATION_POLICY,
    GeneratedMechanicalEnergyProblem,
    GeneratedPowerProblem,
    GeneratedWorkEnergyMetadata,
    GeneratedWorkEnergyProblem,
    GeneratedWorkEnergyTheoremProblem,
    GeneratedWorkProblem,
    WorkEnergyDifficultyProfile,
    WorkEnergyGenerationFamily,
    WorkEnergyGenerationInput,
    WorkEnergyGenerationPolicy,
    WorkEnergyProblemFactory,
)
from .work_energy_power_generation import (
    GENERATOR_ID as WORK_ENERGY_GENERATOR_ID,
)
from .work_energy_power_generation import (
    GENERATOR_VERSION as WORK_ENERGY_GENERATOR_VERSION,
)
from .work_energy_power_generation import (
    POLICY_VERSION as WORK_ENERGY_GENERATION_POLICY_VERSION,
)
from .work_energy_power_solver import (
    SOLVER_ID as WORK_ENERGY_SOLVER_ID,
)
from .work_energy_power_solver import (
    SOLVER_VERSION as WORK_ENERGY_SOLVER_VERSION,
)
from .work_energy_power_solver import (
    VALIDATION_TOLERANCE as WORK_ENERGY_VALIDATION_TOLERANCE,
)
from .work_energy_power_solver import (
    FailureReason as WorkEnergyFailureReason,
)
from .work_energy_power_solver import (
    WorkEnergySolveError,
    WorkEnergySolver,
)

__all__ = [
    "Impulse",
    "KineticEnergy",
    "BodyMomentumResult",
    "Kilograms",
    "MetresPerSecond",
    "Momentum",
    "MomentumChange",
    "MomentumBody",
    "MomentumScenario",
    "MomentumImpulseSolution",
    "MomentumImpulseSolver",
    "MomentumChangeInput",
    "MomentumChangeResult",
    "ImpulseResult",
    "ForceTimeInput",
    "ForceTimeResult",
    "ContactTimeResult",
    "MomentumImpulseRelationshipSolver",
    "DEFAULT_MOMENTUM_PROBLEM_GENERATION_POLICY",
    "GeneratedCollisionProblem",
    "GeneratedContactTimeProblem",
    "GeneratedForceFromMomentumChangeProblem",
    "GeneratedImpulseForceTimeProblem",
    "GeneratedInitialMomentumProblem",
    "GeneratedMomentumChangeProblem",
    "MomentumGeneratedProblem",
    "MomentumGenerationFamily",
    "MomentumProblemDifficultyProfile",
    "MomentumProblemFactory",
    "MomentumProblemGenerationInput",
    "MomentumProblemGenerationPolicy",
    "CollisionClassification",
    "ConstrainedCollisionSolution",
    "ConstrainedMomentumSolver",
    "DerivedFinalBodyState",
    "CommonFinalVelocityConstraint",
    "CompleteFinalStateConstraint",
    "FinalBodyState",
    "InteractionConstraint",
    "InteractionConstraintKind",
    "KnownFinalVelocityConstraint",
    "MomentumInteraction",
    "BodyDynamicsResult",
    "ComponentSign",
    "ConnectedBodiesResult",
    "ContactResult",
    "FailureReason",
    "ForceResult",
    "FrictionResult",
    "GRAVITATIONAL_CONSTANT",
    "GravitationalResult",
    "NewtonSolveError",
    "NewtonSolver",
    "ResultantResult",
    "SOLVER_ID",
    "SOLVER_VERSION",
    "StraightStringRequest",
    "VALIDATION_TOLERANCE",
    "WeightResult",
    "MomentumQuestionGenerator",
    "MomentumQuestionOptions",
    "MomentumQuestionTemplate",
    "DEFAULT_NEWTON_GENERATION_POLICY",
    "DEFAULT_NEWTON_PROBLEM_FACTORY",
    "GeneratedConnectedBodiesProblem",
    "GeneratedContactProblem",
    "GeneratedEquilibriumProblem",
    "GeneratedGravitationProblem",
    "GeneratedNewtonProblem",
    "GeneratedNewtonIIProblem",
    "GeneratedThirdLawProblem",
    "GeneratedUnknownForceProblem",
    "GeneratedWeightProblem",
    "GENERATOR_ID",
    "GENERATOR_VERSION",
    "NewtonDifficultyProfile",
    "NewtonGenerationFamily",
    "NewtonGenerationInput",
    "NewtonGenerationPolicy",
    "NewtonGeneratedMetadata",
    "NewtonGeneratedProblem",
    "NewtonProblemFactory",
    "NEWTON_QUESTION_GENERATOR_ID",
    "NEWTON_QUESTION_GENERATOR_VERSION",
    "NewtonCalculationQuestionGenerator",
    "NewtonCalculationTemplate",
    "NewtonQuestionGenerator",
    "NewtonQuestionOptions",
    "NEWTON_CONCEPTUAL_GENERATOR_ID",
    "NEWTON_CONCEPTUAL_GENERATOR_VERSION",
    "NewtonConceptualQuestionGenerator",
    "NewtonConceptualQuestionOptions",
    "NewtonConceptualTemplate",
    "NewtonConceptualOptions",
    "NewtonQuestionTemplate",
    "POLICY_VERSION",
    "ConceptualQuestionOptions",
    "ConceptualTemplate",
    "MomentumConceptualQuestionGenerator",
    "DEFAULT_MOMENTUM_GENERATION_POLICY",
    "MomentumDifficultyProfile",
    "MomentumGenerationPolicy",
    "MomentumScenarioFactory",
    "MomentumScenarioFamily",
    "MomentumScenarioGenerationInput",
    "PhysicalDirection",
    "PositiveAxis",
    "Newtons",
    "Seconds",
    "SystemBoundary",
    "DEFAULT_GENERATION_POLICY",
    "DifficultyProfile",
    "ScenarioFamily",
    "ScenarioGenerationInput",
    "VerticalProjectileGenerationPolicy",
    "VerticalProjectileScenarioFactory",
    "AlongPlaneWorkInput",
    "AngleDegrees",
    "AveragePowerInput",
    "ConstantSpeedPowerInput",
    "ContactCondition",
    "Displacement",
    "EnergyState",
    "ForceAlongMotion",
    "ForceEnergyClassification",
    "ForceMagnitude",
    "GravitationalFieldMagnitude",
    "HeightState",
    "KineticState",
    "Mass",
    "MassFlowRate",
    "MechanicalEnergyContext",
    "NetWorkInput",
    "PumpingPowerInput",
    "ReferenceLevel",
    "RelativeHeight",
    "SignedEnergy",
    "SignedForce",
    "Speed",
    "SurfaceContext",
    "TimeInterval",
    "WorkEnergyUnknownValue",
    "WorkContribution",
    "WorkEnergyAssumptions",
    "WorkEnergyContext",
    "WorkEnergyScenario",
    "WORK_ENERGY_SOLVER_ID",
    "WORK_ENERGY_SOLVER_VERSION",
    "WORK_ENERGY_VALIDATION_TOLERANCE",
    "WorkEnergyFailureReason",
    "WorkEnergySolveError",
    "WorkEnergySolver",
    "DEFAULT_WORK_ENERGY_GENERATION_POLICY",
    "WORK_ENERGY_GENERATOR_ID",
    "WORK_ENERGY_GENERATOR_VERSION",
    "WORK_ENERGY_GENERATION_POLICY_VERSION",
    "GeneratedMechanicalEnergyProblem",
    "GeneratedPowerProblem",
    "GeneratedWorkEnergyMetadata",
    "GeneratedWorkEnergyProblem",
    "GeneratedWorkEnergyTheoremProblem",
    "GeneratedWorkProblem",
    "WorkEnergyDifficultyProfile",
    "WorkEnergyGenerationFamily",
    "WorkEnergyGenerationInput",
    "WorkEnergyGenerationPolicy",
    "WorkEnergyProblemFactory",
]
